# Generated by Django 2.2.14 on 2020-11-30 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='column',
            field=models.CharField(default='', max_length=100),
        ),
    ]
