# Generated by Django 3.0.3 on 2020-10-13 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_auto_20201013_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='seat',
            field=models.CharField(max_length=100),
        ),
    ]
