# Generated by Django 2.2.14 on 2020-12-01 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_remove_ticket_product_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='mobilenumber',
            field=models.CharField(default='', max_length=100),
        ),
    ]
