# Generated by Django 3.0.3 on 2020-10-15 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_movie_basic_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('card_number', models.IntegerField(default='')),
                ('cvv', models.IntegerField(default='')),
                ('CardHolder_name', models.CharField(max_length=100)),
                ('amount', models.IntegerField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Theatre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Theatre_name', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
