# Generated by Django 2.2.14 on 2020-12-01 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_auto_20201201_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mobilenumber',
            field=models.IntegerField(default=''),
        ),
    ]
