# Generated by Django 2.2.14 on 2020-12-01 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_auto_20201201_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='post_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
