# Generated by Django 2.2.14 on 2020-12-01 07:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_ticket_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
